// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxpsavlzvnuqalisypfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4cHNhdmx6dm51cWFsaXN5cGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjI3OTAsImV4cCI6MjA3MDIzODc5MH0.SuvyuS0-MlfP0M_tSRL8YTHvDb0z9dqCnPtgvFR37t4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});